services:

  postgres:
    image: postgres:15
    container_name: koinz_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - koinz_net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: koinz_ch
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - chdata:/var/lib/clickhouse
    networks:
      - koinz_net

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    command: >
      /bin/bash -c "
        /opt/spark/sbin/start-master.sh && 
        tail -f /opt/spark/logs/*
      "
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CLICKHOUSE_JDBC_URL: jdbc:clickhouse://clickhouse:8123/${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:7077:7077"
    volumes:
      - ./jars/clickhouse-jdbc.jar:/opt/spark/jars/clickhouse-jdbc.jar
      - ./jars/postgresql.jar:/opt/spark/jars/postgresql.jar
    networks:
      - koinz_net
    depends_on:
      - postgres
      - clickhouse

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    command: >
      /bin/bash -c "
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/*
      "
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CLICKHOUSE_JDBC_URL: jdbc:clickhouse://clickhouse:8123/${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    depends_on:
      - spark-master
    volumes:
      - ./jars/clickhouse-jdbc.jar:/opt/spark/jars/clickhouse-jdbc.jar
      - ./jars/postgresql.jar:/opt/spark/jars/postgresql.jar
    networks:
      - koinz_net

volumes:
  pgdata:
  chdata:

networks:
  koinz_net:
    driver: bridge
