services:
  postgres:
    image: postgres:15
    container_name: koinz_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: alam
      POSTGRES_PASSWORD: fdsajkl;pg
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: koinz_ch
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: alam
      CLICKHOUSE_PASSWORD: fdsajkl;ch
      CLICKHOUSE_DB: chdb
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - chdata:/var/lib/clickhouse

  spark-master:
    image: apache/spark:latest
    ports:
      - "8080:8080" # Spark UI
      - "7077:7077" # Spark Master internal communication
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-logs:/opt/apache/spark/logs

  #TODO - spark

volumes:
  pgdata:
  chdata:
