[project]
name = "pg_ch_incremental_loader"
version = "0.1.0"
description = "koinz DE task"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.1.3",
    "clickhouse-connect>=0.10.0",
    "ipython>=9.7.0",
    "psycopg2-binary>=2.9.11",
    "pyspark>=4.0.1",
]
